cemak/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.views import (
    LoginView, SignupView, LogoutView, PasswordResetView, EmailView
)



urlpatterns = [
    # cemak
    path('', homeView, name='home'),
    path('noticias/<str:manchete>/', noticiasView, name='noticias'),
    path('aulas/', alunoView, name='aulas'),
    
    
    
    #path('eventos/', eventosView, name='eventos'),
    #path('campanhas/', campanhasView, name='campanhas'),
    
    # allauth
    path('account/', include(('allauth.urls', 'auth'), namespace='auth')),
    path('account/login/', LoginView.as_view(), name='account_login'),
    path('account/signup/', SignupView.as_view(), name='account_signup'),
    path('account/logout/', LogoutView.as_view(), name='account_logout'),
    path('account/password/reset/', PasswordResetView.as_view(), name='account_reset_password'),
    path('account/email/', EmailView.as_view(), name='account_email'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cemak.urls')),
]

cemak/models.py
from django.db import models

class Noticia(models.Model):
    manchete = models.CharField(max_length=200)
    materia = models.CharField(max_length=1000)
    link_imagem = models.URLField(null=True)
    imagem = models.ImageField('imagem_noticia',upload_to='Imagens',null=True)
    autor = models.CharField(max_length=200)
    data = models.DateTimeField(null=True, auto_now_add=True)
    categoria = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Notícias'
        verbose_name = 'Notícia'

    def validacao(self):
        if len(self.manchete) < 8:
            raise ValueError('A manchete deve ter pelo menos 8 caracteres')
    
    def __str__(self):
        return self.manchete


class Video(models.Model):
    titulo = models.CharField(max_length=200)
    link_video = models.URLField(null=True)
    thumbnail = models.ImageField('Thumbnail',upload_to='Thumbnail', null=True, blank=True)
    descricao = models.CharField(max_length=500)
    data = models.DateTimeField(null=True, auto_now_add=True)
    autor = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Vídeos'
        verbose_name = 'Vídeo'

    def __str__(self):
        return self.titulo


class Banner(models.Model):
    nome = models.CharField(verbose_name='Nome banner', max_length=10, null=False, blank=False)

    CHOICES = (
    ("4", "1"),
    ("3", "2"),
    ("2", "3"),
    ("1", "4"),
    )
    posicao = models.CharField('', max_length=1, choices=CHOICES, null=True, blank=True, unique=True)
    imagem = models.ImageField('Banner', upload_to='Banner', null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Banners'

    def str(self):
        return self.nome




class Footer(models.Model):
    endereco =models.CharField(verbose_name='Endereço',max_length=100,null=False,)
    localizacao =models.CharField(verbose_name='localização',max_length=100,null=False)
    contato = models.IntegerField(verbose_name='Contato',default=(' +55 (00) 9'))
    saiba_mais = models.CharField(verbose_name='Saiba mais',max_length=100,null=False)

    class Meta:
        verbose_name = 'Rodapé'

    def str(self) -> str:
        return self.endereco
    

cemak/views.py
from django.shortcuts import render,redirect,get_object_or_404

from django.contrib.auth.decorators import login_required

from rest_framework import viewsets
from rest_framework.decorators import api_view

from .models import * 
from .serializers import * 
from .forms import * 


footer = Footer.objects.all()

def homeView(request):
    banner = Banner.objects.order_by('-posicao')
    noticias = Noticia.objects.order_by('-data')
    context={'banner':banner, 'noticias':noticias, 'footer':footer}
    return render(request, 'index.html', context)


def noticiasView(request, manchete):
    noticias = Noticia.objects.get(manchete=manchete)
    context={'noticias':noticias, 'footer':footer}
    return render(request, 'noticias.html', context)



@login_required
def alunoView(request):
    video = Video.objects.order_by('-data')
    context={'video':video, 'footer':footer}
    return render(request, 'area-do-aluno.html', context)





   
        

cemak/templates/area-do-aluno.html
{% extends 'index.html' %}
{% load static %}


{% block 'section' %}
<br>
<br>
    <h1 style="margin-left: 50px;">Area do Aluno</h1>
<br>
<br>
<br>
    {% for item in video %}
        <div style="display: flex;justify-content: center;align-items: center;flex-flow: row wrap; width: 23%;margin-left: 20px;">
            <a href="{{item.link_video}}" target="_blank" style="color: black; text-align: center;">
                <div>
                    <div style="width: 290px; height: 200px;display: flex; justify-content: center; align-items: center; border: 2px solid green;">
                        <img src="{{item.thumbnail.url}}" alt="{{item.titulo}}" width="99%" height="99%">
                    </div>
                    <br>
                    {{item.titulo}}
                    <br>
                    <br>
                    <div>
                        {{item.autor}}
                    </div>
                    <br>
                </div>
           </a>    
        </div>
    {% endfor %}
<br>
<br>
<br>
{% endblock 'section' %}

cemak/templates/noticias.html
{% extends 'index.html' %}
{% load static %}


{% block 'section' %}


    
    {{noticias.manchete}}
    {{noticias.materia}}
    {{noticias.link_imagem}}
    <img src="{{noticias.imagem.url}}" alt="{{noticias.manchete}}" width="100px">
    {{noticias.autor}}
    {{noticias.data}}
    {{noticias.categoria}}


{% endblock 'section' %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/reset.css' %}">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="shortcut icon" href="{% static '/media/logopagina(2).png' %}">
    <title>HNL - CEMAK</title>
</head>

<body>
    <header class="header">
        <div class="imgHeader">
            <a href="{% url 'home' %}"><img src="{% static '/media/logowhite.png' %}" alt="logo"></a>
        </div>
        <nav>
            <ul>
                <li class="botao"><a href="#">Ensino</a>
                    <i class="fa-solid fa-chevron-down"></i>
                    <div class="subMenu1">
                        <ul>
                            <li class="hoverMenu2"><a href="#">Treinamento HNL</a>
                                <i class="fa-solid fa-chevron-right"></i>
                                <div class="subMenu2">
                                    <ul>
                                        <li>Cuidados Paliativos</li>
                                        <li>Parada Cardiorrespiratória(PCR)</li>
                                    </ul>
                                </div>
                            </li>
                            <li><a href="{% url 'auth:account_login' %}">Área do Aluno CEMAK</a></li>
                            <li class="hoverMenu2"><a href="#">Cursos CEMAK</a>
                                <i class="fa-solid fa-chevron-right"></i>
                                <div class="subMenu2">
                                    <ul>
                                        <li>Capacitação de urgência e emergência para técnicos de enfermagem</li>
                                        <li>Curso prático de manipulação de cateteres venosos centrais e hipodermóclise
                                        </li>
                                        <li>Aperfeiçoamente prático no tratamento de feridas e estomias</li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="botao"><a href="#">Pesquisador</a>
                    <i class="fa-solid fa-chevron-down"></i>
                    <div class="subMenu1">
                        <ul>
                            <li><a href="https://cemak.org/wp-content/uploads/2022/06/Fluxo-de-Pesquisa_HNL.pdf">Fluxo
                                    de Pesquisa</a></li>
                            <li><a href="#">Termo de Responsabilidade</a></li>
                            <li><a href="#">Carta de anuência setorial com autorização do uso de dados</a></li>
                            <li><a href="#">Carta de anuência do SAME</a></li>
                        </ul>
                    </div>
                </li>
                <li class="botao" id="borda"><a href="#">Eventos</a></li>
                <li class="botao" id="borda"><a href="#">Campanhas</a></li>
            </ul>

        </nav>
        <div class="imgLaureano">
            <img src="{% static 'media/logoLaureano.png' %}" alt="Logo laureano">
        </div>
    </header>

    {% block 'section' %}

    <section class="alinhar">
        <div class="carrosel">
            <div class="slides">
                <div class="passador">

                </div>

                <div id="atual" class="imagens">
                    <img src="{% static 'media/img2.avif' %}" alt="imagem 1">
                </div>
                <div class="imagens">
                    <img src="{% static 'media/img1.jpg' %}" alt="imagem 2">
                </div>
                <div class="imagens">
                    <img src="{% static 'media/img3.avif' %}" alt="imagem 3">
                </div>
            </div>
        </div>
        <div class="doacao">
            <div class="imgDoacao">
                <img src="{% static '/media/logoLaureano.png' %}">
            </div>
            <div class="textoDoacao">
                <h2>Faça sua doação já!</h2>
                <p>Clique aqui para saber mais</p>
            </div>
        </div>
    </section>
    {% for item in noticias %}
                <a href="{% url 'noticias' item.manchete %}" style='color: black;'>
                    <div style="display: flex; justify-content: start; align-items: center; width: 20%; height: 10%; border-bottom: 3px solid green;">
                        <img src="{{item.imagem.url}}" alt="{{item.manchete}}" width="120px" height="100px">   
                       <div >{{item.manchete}}</div> 
                </div>
                </a>
                <br>
                <br>
                {% endfor %}
    {% endblock 'section' %}
        </div>
    <footer class="footer">
        <div class="logoCemak">
            <img src="{% static '/media/logowhite.png' %}" alt="">
        </div>
        <div class="socialCemak">
            <h2>Redes de contato</h2>
            <nav>
                <ul>
                    <li><i class="fa-brands fa-youtube"></i></li>
                    <li><i class="fa-brands fa-instagram"></i></li>
                    <li><i class="fa-brands fa-twitter"></i></li>
                    <li><i class="fa-brands fa-facebook"></i></li>
                </ul>
            </nav>
        </div>
        <div class="ouvidoriaCemak">
            <h2>SAC</h2>
            <p>4002-8922</p>
        </div>
    </footer>



    <script src="{% static '/js/script.js' %}"></script>
</body>

</html>